import argparse
from wandb_train import main

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--dataset_name", type=str, default="assist2015")
    parser.add_argument("--model_name", type=str, default="lareskt_v7_2")
    parser.add_argument("--emb_type", type=str, default="qid")
    parser.add_argument("--save_dir", type=str, default="saved_model")
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--fold", type=int, default=0)
    parser.add_argument("--dropout", type=float, default=0.1)
    parser.add_argument("--d_model", type=int, default=256)
    parser.add_argument("--d_ff", type=int, default=256)
    parser.add_argument("--num_attn_heads", type=int, default=4)
    parser.add_argument("--n_blocks", type=int, default=1)
    parser.add_argument("--learning_rate", type=float, default=1e-4)
    parser.add_argument("--batch_size", type=int, default=64)
    parser.add_argument("--num_epochs", type=int, default=100)
    parser.add_argument("--mean_recurrence", type=int, default=3)
    parser.add_argument("--sampling_scheme", type=str, default="uniform")
    parser.add_argument("--state_init_method", type=str, default="zero")
    parser.add_argument("--state_std", type=float, default=0.02)
    parser.add_argument("--state_scale", type=float, default=1.0)
    parser.add_argument("--adapter_type", type=str, default="linear")
    parser.add_argument("--tau", type=float, default=0.2)
    parser.add_argument("--alpha", type=float, default=0.0)
    parser.add_argument("--gamma", type=float, default=0.0)
    parser.add_argument("--same_step", type=int, default=1)
    parser.add_argument("--query_fusion", type=str, default="gate")
    parser.add_argument("--use_wandb", type=int, default=1)
    parser.add_argument("--add_uuid", type=int, default=0)
    parser.add_argument("--gpu_ids", type=str, default="")
    args = parser.parse_args()
    params = vars(args)
    params["same_step"] = bool(params["same_step"])
    main(params)
